version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/stop-server.sh
      timeout: 180
      runas: root
  Install:
    - location: scripts/start-server.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/post-deploy.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-frontend.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 180
      runas: root
